dist: xenial
language: c
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y fakeroot
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y libncurses-dev
script: make BINDIR=/usr/bin MANDIR=/usr/share/man DISKDEFS=/etc/diskdefs all && fakeroot mkdir -p ${HOME}/sysroot/etc ${HOME}/sysroot/usr/bin ${HOME}/sysroot/usr/share/man/man1 && fakeroot make BINDIR=${HOME}/sysroot/usr/bin MANDIR=${HOME}/sysroot/usr/share/man DISKDEFS=${HOME}/sysroot/etc/diskdefs install
